/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vyom;

/**
 *
 * @author jalatif
 */
public class FilePath extends javax.swing.JFrame {

		public static String fileadd = "";
		/**
		 * Creates new form FilePath
		 */
		public FilePath() {
				initComponents();
		}

		/**
		 * This method is called from within the constructor to initialize the
		 * form. WARNING: Do NOT modify this code. The content of this method is
		 * always regenerated by the Form Editor.
		 */
		@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FC_Filepath = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FC_Filepath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FC_FilepathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FC_Filepath, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FC_Filepath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

		private void FC_FilepathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FC_FilepathActionPerformed
				// TODO add your handling code here
			fileadd = String.valueOf(FC_Filepath.getSelectedFile());
			System.out.println(fileadd);
			setVisible(false);
				
		}//GEN-LAST:event_FC_FilepathActionPerformed

		/**
		 * @param args the command line arguments
		 */
		public static void main(String args[]) {
				/*
				 * Set the Nimbus look and feel
				 */
				//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
				 * If Nimbus (introduced in Java SE 6) is not available, stay
				 * with the default look and feel. For details see
				 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
				 */
				try {
						for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
								if ("Nimbus".equals(info.getName())) {
										javax.swing.UIManager.setLookAndFeel(info.getClassName());
										break;
								}
						}
				} catch (ClassNotFoundException ex) {
						java.util.logging.Logger.getLogger(FilePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				} catch (InstantiationException ex) {
						java.util.logging.Logger.getLogger(FilePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				} catch (IllegalAccessException ex) {
						java.util.logging.Logger.getLogger(FilePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				} catch (javax.swing.UnsupportedLookAndFeelException ex) {
						java.util.logging.Logger.getLogger(FilePath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
				}
				//</editor-fold>

				/*
				 * Create and display the form
				 */
				java.awt.EventQueue.invokeLater(new Runnable() {

						public void run() {
								new FilePath().setVisible(true);
						}
				});
		}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FC_Filepath;
    // End of variables declaration//GEN-END:variables
}
